"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-container",
        skip_rules=(
            # PS-503 — examples/{03_python_api,05_env_snapshot}_out/ need
            # FINISHED_SUCCESS/<id>/ artefacts. Both examples wrap @stx.session
            # which needs the scitex umbrella. Tracked: run them once per
            # release and commit the output dirs.
            "PS-503",
            # §6 — 37/51 Python APIs unmapped to MCP tools (apptainer_*).
            # Real architectural-parity gap; per-API decision needed.
            "§6",
        ),
    )
